---
abstract: 'Automatic Trait Loading and Resolution for'
author:
  - 'Rafael Kitover <rkitover@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-Component-Traits
no_index:
  directory:
    - inc
    - t
provides:
  CatalystX::Component::Traits:
    file: lib/CatalystX/Component/Traits.pm
    version: 0.02
requires:
  Catalyst::Runtime: 5.80005
  List::MoreUtils: 0
  Moose::Autobox: 0
  MooseX::Traits::Pluggable: 0.04
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
