---
abstract: 'Automatic Trait Loading and Resolution for Catalyst Components'
author:
  - 'Rafael Kitover, C<< <rkitover@cpan.org> >>'
  - 'Rafael Kitover <bobtfish@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Module::Pluggable: 3.9
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-Component-Traits
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Runtime: 5.80005
  Class::Load: 0
  List::MoreUtils: 0
  MooseX::Traits::Pluggable: 0.08
  Scalar::Util: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bobtfish/catalystx-component-traits.git
version: 0.17
